apiVersion: v1
kind: Pod
metadata:
  name: echo-env
spec:
  containers:
  - name: echo-env
    image: echo_env:latest
    imagePullPolicy: Never
    env:
    - name: MY_ENV_VARIABLE
      value: "Hello from the environment"

